---
title: "Final Assignment Analysis of Spatiotemporal Data"
subtitle: "Spatial point pattern analysis of wind turbines in the precincts of NRW"
author: "Alexander Pilz"
date: "2023-01-30"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

## Introduction
```{r importLibraries, echo=TRUE}
#import libraries
library(sf) 
library(raster)
library(spatstat)
library(plyr)
```
```{r ingestDatasets, include=TRUE}

```

## Datasets
```{r summarizePrecincts, echo=TRUE, fig.height=8, fig.width=8}
#import precincts
precincts <- st_read("data/dvg2_EPSG25832_Shape/dvg2rbz_nw.shp")
#union precincts
precinctsUnion <- st_union(precincts)
summary(precincts)
```
```{r plotPrecincts, echo=FALSE, fig.height=8, fig.width=8}
#plot precincts of NRW
plot(st_geometry(precincts), main = "Precincts of NRW", sub = "Fig. ")
precinctsCentroids = st_coordinates(st_centroid(st_geometry(precincts)))
text(precinctsCentroids, labels = precincts$GN, col = "blue")
```
```{r summarizeTurbines, echo=TRUE}
#import wind turbines
windTurbines <- st_read("data/OpenEE-Windenergie_EPSG25832_Shape/Windbetrieb_Standorte.shp")
summary(windTurbines)
```
```{r summarizeYields, echo=TRUE, fig.height=8, fig.width=8}
#import potential yields
potentialYields <- raster("data/Energieleistungsdichte-100m_EPSG25832_TIFF/en_100m_klas.tif")
summary(potentialYields)
plot(potentialYields, sub = "Fig. ", main = "Potential yields of NRW")
```

```{r subsetWindTurbines, echo=TRUE}
#create subset of wind turbines for each precinct
windTurbinesArnsberg <- st_intersection(windTurbines, precincts[precincts$GN == "Arnsberg",])
windTurbinesDetmold <- st_intersection(windTurbines, precincts[precincts$GN == "Detmold",])
windTurbinesKöln <- st_intersection(windTurbines, precincts[precincts$GN == "Köln",])
windTurbinesDüsseldorf <- st_intersection(windTurbines, precincts[precincts$GN == "Düsseldorf",])
windTurbinesMünster <- st_intersection(windTurbines, precincts[precincts$GN == "Münster",])

#create planar point patterns from wind turbine subsets
pppArnsberg <- as.ppp(c(st_geometry(precincts[precincts$GN == "Arnsberg",]), st_geometry(windTurbinesArnsberg)))
pppDetmold <- as.ppp(c(st_geometry(precincts[precincts$GN == "Detmold",]), st_geometry(windTurbinesDetmold)))
pppKöln <- as.ppp(c(st_geometry(precincts[precincts$GN == "Köln",]), st_geometry(windTurbinesKöln)))
pppDüsseldorf <- as.ppp(c(st_geometry(precincts[precincts$GN == "Düsseldorf",]), st_geometry(windTurbinesDüsseldorf)))
pppMünster <- as.ppp(c(st_geometry(precincts[precincts$GN == "Münster",]), st_geometry(windTurbinesMünster)))

precintNames <- c("Arnsberg", "Detmold", "Köln", "Düsseldorf", "Münster")
windTurbineCounts <- c(pppArnsberg$n, pppDetmold$n, pppKöln$n, pppDüsseldorf$n, pppMünster$n)
windTurbineDensities <- c(pppArnsberg$n/(as.numeric(st_area(precincts[precincts$GN == "Arnsberg",]))/1000000), 
                          pppDetmold$n/(as.numeric(st_area(precincts[precincts$GN == "Detmold",]))/1000000), 
                          pppKöln$n/(as.numeric(st_area(precincts[precincts$GN == "Köln",]))/1000000),
                          pppDüsseldorf$n/(as.numeric(st_area(precincts[precincts$GN == "Düsseldorf",]))/1000000),
                          pppMünster$n/(as.numeric(st_area(precincts[precincts$GN == "Münster",]))/1000000))
precintAreas <- c(as.numeric(st_area(precincts[precincts$GN == "Arnsberg",]))/1000000,
                  as.numeric(st_area(precincts[precincts$GN == "Detmold",]))/1000000,
                  as.numeric(st_area(precincts[precincts$GN == "Köln",]))/1000000,
                  as.numeric(st_area(precincts[precincts$GN == "Düsseldorf",]))/1000000,
                  as.numeric(st_area(precincts[precincts$GN == "Münster",]))/1000000)

precinctDf <- data.frame(precintNames, precintAreas, windTurbineCounts, windTurbineDensities)
colnames(precinctDf) <- c('Precinct','Area in km²','Turbine count', 'Turbine density')

#compute densities of wind turbines for each precinct
densityArnsberg <- density(pppArnsberg, sigma = bw.diggle, diggle = TRUE, edge = TRUE)
densityDetmold <- density(pppDetmold, sigma = bw.diggle, diggle = TRUE, edge = TRUE)
densityKöln <- density(pppKöln, sigma = bw.diggle, diggle = TRUE, edge = TRUE)
densityDüsseldorf <- density(pppDüsseldorf, sigma = bw.diggle, diggle = TRUE, edge = TRUE)
densityMünster <- density(pppMünster, sigma = bw.diggle, diggle = TRUE, edge = TRUE)
```

```{r plotWindTurbines, echo=FALSE, fig.show='hold', out.width='50%', fig.height=8, message=FALSE}
barplot(windTurbineCounts, main = "Ammount of wind turbines per precinct", xlab = "Count", ylab = "Precinct", names.arg = precintNames, sub = "Fig.")
barplot(windTurbineDensities, main = "Density of wind turbines per precinct", xlab = "Density per km²", ylab = "Precinct", names.arg = precintNames, sub = "Fig.")
show(precinctDf)

par(mar=c(1, 1, 1, 1))
plot(st_geometry(precincts[precincts$GN == "Arnsberg",]), main = "Wind turbines - Arnsberg", sub = "Fig. ")
plot(st_geometry(windTurbinesArnsberg), pch = 3, col = 'red', add = TRUE)

plot(densityArnsberg, main = "Wind turbine density - Arnsberg", sub = "Fig. ")
plot(st_geometry(precincts[precincts$GN == "Arnsberg",]), add=TRUE)

plot(st_geometry(precincts[precincts$GN == "Detmold",]), main = "Wind turbines - Detmold", sub = "Fig. ")
plot(st_geometry(windTurbinesDetmold), pch = 3, col = 'red', add = TRUE)

plot(densityDetmold, main = "Wind turbine density - Detmold", sub = "Fig. ")
plot(st_geometry(precincts[precincts$GN == "Detmold",]), add=TRUE)

plot(st_geometry(precincts[precincts$GN == "Köln",]), main = "Wind turbines - Köln", sub = "Fig. ")
plot(st_geometry(windTurbinesKöln), pch = 3, col = 'red', add = TRUE)

plot(densityKöln, main = "Wind turbine density - Köln", sub = "Fig. ")
plot(st_geometry(precincts[precincts$GN == "Köln",]), add=TRUE)

plot(st_geometry(precincts[precincts$GN == "Düsseldorf",]), main = "Wind turbines - Düsseldorf", sub = "Fig. ")
plot(st_geometry(windTurbinesDüsseldorf), pch = 3, col = 'red', add = TRUE)

plot(densityDüsseldorf, main = "Wind turbine density - Düsseldorf", sub = "Fig. ")
plot(st_geometry(precincts[precincts$GN == "Düsseldorf",]), add=TRUE)

plot(st_geometry(precincts[precincts$GN == "Münster",]), main = "Wind turbines of Münster precinct", sub = "Fig. ")
plot(st_geometry(windTurbinesMünster), pch = 3, col = 'red', add = TRUE)

plot(densityMünster, main = "Wind turbine density of Münster precinct", sub = "Fig. ")
plot(st_geometry(precincts[precincts$GN == "Münster",]), add=TRUE)
```

## Analysis
### Part I - Preliminary testing
```{r gFunction, echo=FALSE, message=FALSE, warning=FALSE}
#compute G-, F- and J-function for precinct Arnsberg
gEnvArnsberg <- envelope(pppArnsberg, fun = Gest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
fEnvArnsberg <- envelope(pppArnsberg, fun = Fest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
jEnvArnsberg <- envelope(pppArnsberg, fun = Jest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)

#compute G-, F- and J-function for precinct Detmold
gEnvDetmold <- envelope(pppDetmold, fun = Gest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
fEnvDetmold <- envelope(pppDetmold, fun = Fest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
jEnvDetmold <- envelope(pppDetmold, fun = Jest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)

#compute G-, F- and J-function for precinct Arnsberg
gEnvKöln <- envelope(pppKöln, fun = Gest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
fEnvKöln <- envelope(pppKöln, fun = Fest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
jEnvKöln <- envelope(pppKöln, fun = Jest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)

#compute G-, F- and J-function for precinct Arnsberg
gEnvDüsseldorf <- envelope(pppDüsseldorf, fun = Gest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
fEnvDüsseldorf <- envelope(pppDüsseldorf, fun = Fest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
jEnvDüsseldorf <- envelope(pppDüsseldorf, fun = Jest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)

#compute G-, F- and J-function for precinct Arnsberg
gEnvMünster <- envelope(pppMünster, fun = Gest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
fEnvMünster <- envelope(pppMünster, fun = Fest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
jEnvMünster <- envelope(pppMünster, fun = Jest, nsim = 99, clipdata = TRUE, correction = "best", verbose = FALSE)
```
```{r gFunctionPlot, echo=FALSE, fig.show='hold', out.width='50%', fig.height=8, message=FALSE, warning=FALSE}
#plot G-function for precincts
plot(gEnvArnsberg, main = "G-function - Arnsberg", sub = "Fig. ")
plot(gEnvDetmold, main = "G-function - Detmold", sub = "Fig. ")
plot(gEnvKöln, main = "G-function - Köln", sub = "Fig. ")
plot(gEnvDüsseldorf, main = "G-function - Düsseldorf", sub = "Fig. ")
plot(gEnvMünster, main = "G-function - Münster", sub = "Fig. ")
```
```{r fFunctionPlot, echo=FALSE, fig.show='hold', out.width='50%', fig.height=8, message=FALSE, warning=FALSE}
#plot F-function for precincts
plot(fEnvArnsberg, main = "F-function - Arnsberg", sub = "Fig. ")
plot(fEnvDetmold, main = "F-function - Detmold", sub = "Fig. ")
plot(fEnvKöln, main = "F-function - Köln", sub = "Fig. ")
plot(fEnvDüsseldorf, main = "F-function - Düsseldorf", sub = "Fig. ")
plot(fEnvMünster, main = "F-function - Münster", sub = "Fig. ")
```
```{r jFunctionPlot, echo=FALSE, fig.height=8, fig.show='hold', message=FALSE, warning=FALSE, out.width='50%'}
#plot J-function for precincts
plot(jEnvArnsberg, main = "J-function - Arnsberg", sub = "Fig. ", ylim=c(0,12))
plot(jEnvDetmold, main = "J-function - Detmold", sub = "Fig. ", ylim=c(0,12))
plot(jEnvKöln, main = "J-function - Köln", sub = "Fig. ", ylim=c(0,12))
plot(jEnvDüsseldorf, main = "J-function - Düsseldorf", sub = "Fig. ", ylim=c(0,12))
plot(jEnvMünster, main = "J-function - Münster", sub = "Fig. ", ylim=c(0,12))
```

### Part II - Influence of potenial energy yields
```{r cropYields, echo=FALSE, fig.show='hold', out.width='50%', message=FALSE, warning=FALSE}
potentialYieldsArnsbergCropped <- crop(potentialYields, precincts[precincts$GN == "Arnsberg",])
potentialYieldsArnsbergMasked <- mask(potentialYieldsArnsbergCropped, precincts[precincts$GN == "Arnsberg",])

potentialYieldsDetmoldCropped <- crop(potentialYields, precincts[precincts$GN == "Detmold",])
potentialYieldsDetmoldMasked <- mask(potentialYieldsDetmoldCropped, precincts[precincts$GN == "Detmold",])

potentialYieldsKölnCropped <- crop(potentialYields, precincts[precincts$GN == "Köln",])
potentialYieldsKölnMasked <- mask(potentialYieldsKölnCropped, precincts[precincts$GN == "Köln",])

potentialYieldsDüsseldorfCropped <- crop(potentialYields, precincts[precincts$GN == "Düsseldorf",])
potentialYieldsDüsseldorfMasked <- mask(potentialYieldsDüsseldorfCropped, precincts[precincts$GN == "Düsseldorf",])

potentialYieldsMünsterCropped <- crop(potentialYields, precincts[precincts$GN == "Münster",])
potentialYieldsMünsterMasked <- mask(potentialYieldsMünsterCropped, precincts[precincts$GN == "Münster",])
```
```{r plotYields, echo=FALSE, fig.show='hold', out.width='50%', fig.height=8, message=FALSE, warning=FALSE}
plot(potentialYieldsArnsbergMasked, sub = "Fig.", main = "Potential yields - Arnsberg")

plot(potentialYieldsDetmoldMasked, sub = "Fig. ", main = "Potential yields - Detmold")

plot(potentialYieldsKölnMasked, sub = "Fig. ", main = "Potential yields - Köln")

plot(potentialYieldsDüsseldorfMasked, sub = "Fig. ", main = "Potential yields - Düsseldorf")

plot(potentialYieldsMünsterMasked, sub = "Fig. ", main = "Potential yields - Münster")

```
```{r extractYields, echo=TRUE, fig.show='hold', message=FALSE, warning=FALSE, out.width='50%'}
#import precincts
yields <- c("1", "2", "3", "4", "5", "6", "7")

#extract yields
turbinesWithYieldsArnsberg <- as.data.frame(extract(potentialYieldsArnsbergMasked, windTurbinesArnsberg))
colnames(turbinesWithYieldsArnsberg) <- c("DN")

turbinesWithYieldsDetmold <- as.data.frame(extract(potentialYieldsDetmoldMasked, windTurbinesDetmold))
colnames(turbinesWithYieldsDetmold) <- c("DN")

turbinesWithYieldsKöln <- as.data.frame(extract(potentialYieldsKölnMasked, windTurbinesKöln))
colnames(turbinesWithYieldsKöln) <- c("DN")

turbinesWithYieldsDüsseldorf <- as.data.frame(extract(potentialYieldsDüsseldorfMasked, windTurbinesDüsseldorf))
colnames(turbinesWithYieldsDüsseldorf) <- c("DN")

turbinesWithYieldsMünster <- as.data.frame(extract(potentialYieldsMünsterMasked, windTurbinesMünster))
colnames(turbinesWithYieldsMünster) <- c("DN")

#compute turbine count per yield
turbinesWithYieldsArnsbergFreq <- count(turbinesWithYieldsArnsberg) 
colnames(turbinesWithYieldsArnsbergFreq) <- c("potentialYield", "turbineCount")

turbinesWithYieldsDetmoldFreq <- count(turbinesWithYieldsDetmold) 
colnames(turbinesWithYieldsDetmoldFreq) <- c("potentialYield", "turbineCount")

turbinesWithYieldsKölnFreq <- count(turbinesWithYieldsKöln) 
colnames(turbinesWithYieldsKölnFreq) <- c("potentialYield", "turbineCount")

turbinesWithYieldsDüsseldorfFreq <- count(turbinesWithYieldsDüsseldorf) 
colnames(turbinesWithYieldsDüsseldorfFreq) <- c("potentialYield", "turbineCount")

turbinesWithYieldsMünsterFreq <- count(turbinesWithYieldsMünster) 
colnames(turbinesWithYieldsMünsterFreq) <- c("potentialYield", "turbineCount")

#compute pixel counts per yield
potentialYieldsArnsbergCounts <-  as.data.frame(freq(potentialYieldsArnsbergMasked))
colnames(potentialYieldsArnsbergCounts) <- c("potentialYield", "pixelCount")

potentialYieldsDetmoldCounts <-  as.data.frame(freq(potentialYieldsDetmoldMasked))
colnames(potentialYieldsDetmoldCounts) <- c("potentialYield", "pixelCount")

potentialYieldsKölnCounts <-  as.data.frame(freq(potentialYieldsKölnMasked))
colnames(potentialYieldsKölnCounts) <- c("potentialYield", "pixelCount")

potentialYieldsDüsseldorfCounts <-  as.data.frame(freq(potentialYieldsDüsseldorfMasked))
colnames(potentialYieldsDüsseldorfCounts) <- c("potentialYield", "pixelCount")

potentialYieldsMünsterCounts <-  as.data.frame(freq(potentialYieldsMünsterMasked))
colnames(potentialYieldsMünsterCounts) <- c("potentialYield", "pixelCount")

#compute area per yield
potentialYieldsArnsbergCounts$area = (potentialYieldsArnsbergCounts$pixelCount*10000)/1000000
potentialYieldsDetmoldCounts$area = (potentialYieldsDetmoldCounts$pixelCount*10000)/1000000
potentialYieldsKölnCounts$area = (potentialYieldsKölnCounts$pixelCount*10000)/1000000
potentialYieldsDüsseldorfCounts$area = (potentialYieldsDüsseldorfCounts$pixelCount*10000)/1000000
potentialYieldsMünsterCounts$area = (potentialYieldsMünsterCounts$pixelCount*10000)/1000000

#merge turbine counts per yield and pixel counts per yield
potentialYieldsArnsbergCounts <- merge(turbinesWithYieldsArnsbergFreq, potentialYieldsArnsbergCounts, 
                                       by.x = "potentialYield", by.y = "potentialYield")

potentialYieldsDetmoldCounts <- merge(turbinesWithYieldsDetmoldFreq, potentialYieldsDetmoldCounts, 
                                      by.x = "potentialYield", by.y = "potentialYield")

potentialYieldsKölnCounts <- merge(turbinesWithYieldsKölnFreq, potentialYieldsKölnCounts, 
                                      by.x = "potentialYield", by.y = "potentialYield")

potentialYieldsDüsseldorfCounts <- merge(turbinesWithYieldsDüsseldorfFreq, potentialYieldsDüsseldorfCounts, 
                                      by.x = "potentialYield", by.y = "potentialYield")

potentialYieldsMünsterCounts <- merge(turbinesWithYieldsMünsterFreq, potentialYieldsMünsterCounts, 
                                      by.x = "potentialYield", by.y = "potentialYield")

potentialYieldsArnsbergCounts$density = potentialYieldsArnsbergCounts$turbineCount/potentialYieldsArnsbergCounts$area
potentialYieldsDetmoldCounts$density = potentialYieldsDetmoldCounts$turbineCount/potentialYieldsDetmoldCounts$area
potentialYieldsKölnCounts$density = potentialYieldsKölnCounts$turbineCount/potentialYieldsKölnCounts$area
potentialYieldsDüsseldorfCounts$density = potentialYieldsDüsseldorfCounts$turbineCount/potentialYieldsDüsseldorfCounts$area
potentialYieldsMünsterCounts$density = potentialYieldsMünsterCounts$turbineCount/potentialYieldsMünsterCounts$area
```
```{r localDensities, echo=FALSE, fig.show='hold', message=FALSE, warning=FALSE, out.width='50%'}
#possible yields 
yields <- c("1", "2", "3", "4", "5", "6", "7")

#plot local densities
barplot(potentialYieldsArnsbergCounts$density, main = "Local wind turbine densities - Arnsberg", xlab = "Potential yield", ylab = "Wind turbine density", names.arg = potentialYieldsArnsbergCounts$potentialYield, sub = "Fig.")

barplot(potentialYieldsDetmoldCounts$density, main = "Local wind turbine densities - Detmold", xlab = "Potential yield", ylab = "Wind turbine density", names.arg = potentialYieldsDetmoldCounts$potentialYield, sub = "Fig.")

barplot(potentialYieldsKölnCounts$density, main = "Local wind turbine densities - Köln", xlab = "Potential yield", ylab = "Wind turbine density", names.arg = potentialYieldsKölnCounts$potentialYield, sub = "Fig.")

barplot(potentialYieldsDüsseldorfCounts$density, main = "Local wind turbine densities - Düsseldorf", xlab = "Potential yield", ylab = "Wind turbine density", names.arg = potentialYieldsDüsseldorfCounts$potentialYield, sub = "Fig.")

barplot(potentialYieldsMünsterCounts$density, main = "Local wind turbine densities - Münster", xlab = "Potential yield", ylab = "Wind turbine density", names.arg = potentialYieldsMünsterCounts$potentialYield, sub = "Fig.")
```

### Part III - Differences between precincts
## Results
## Sources
